- project:
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - magnum-tempest-plugin-tests-api
    gate:
      queue: magnum
      jobs:
        - magnum-tempest-plugin-tests-api

- job:
    name: magnum-tempest-plugin-tests-api
    parent: magnum-tempest-plugin-base
    vars:
      tox_envlist: all
      tempest_test_regex: ^magnum_tempest_plugin.tests.api
      tempest_exclude_regex: (test_create_list_sign_delete_clusters|test_create_cluster_with_zero_nodes)
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            magnum:
              image_id: fedora-coreos-31.20200323.3.2-openstack.x86_64
              nic_id: public
              keypair_id: default
              flavor_id: ds2G
              master_flavor_id: ds2G
              copy_logs: true
      devstack_localrc:
        # NOTE: extend default glance limit from 1GB
        GLANCE_LIMIT_IMAGE_SIZE_TOTAL: 5000

- job:
    name: magnum-tempest-plugin-base
    description: |
      Magnum functional tests base layer
    parent: devstack-tempest
    required-projects:
      - openstack/magnum
      - openstack/python-magnumclient
      - openstack/heat
      - openstack/barbican
      - openstack/magnum-tempest-plugin
    vars:
      tempest_plugins:
        - magnum-tempest-plugin
      devstack_localrc:
        USE_PYTHON3: true
        MAGNUM_GUEST_IMAGE_URL: https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/31.20200323.3.2/x86_64/fedora-coreos-31.20200323.3.2-openstack.x86_64.qcow2.xz
        MAGNUM_IMAGE_NAME: fedora-coreos-31.20200323.3.2-openstack.x86_64
      devstack_plugins:
        magnum: https://opendev.org/openstack/magnum
        heat: https://opendev.org/openstack/heat
        barbican: https://opendev.org/openstack/barbican
      devstack_services:
        # Disable swift and dependent c-bak service to support upload of .qcow2.xz image in the gate
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        c-bak: false
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^specs/.*$
      - ^install-guide/.*$
      - ^releasenotes/.*$
      - ^dockerfiles/.*$
