---
- project:
    queue: magnum
    templates:
      - check-requirements
      - tempest-plugin-jobs
      - magnum-tempest-plugin-jobs-master
      - magnum-tempest-plugin-jobs-2024-1
      - magnum-tempest-plugin-jobs-2024-2
